vars:
  time_limit: &time_limit 86400 # 24 hrs

defaults: &defaults
  start: shinka/start.sh
  dockerfile: shinka/Dockerfile
  kwargs_type: argparse
  kwargs:
    num_generations: 100
  env_vars: &env_vars
    TIME_LIMIT_SECS: *time_limit

shinka:
  <<: *defaults
  env_vars:
    <<: *env_vars
  
shinka/use_text_feedback:
  <<: *defaults
  env_vars:
    <<: *env_vars
    USE_TEXT_FEEDBACK: true

shinka/use_text_feedback_premium_models:
  <<: *defaults
  env_vars:
    <<: *env_vars
    USE_TEXT_FEEDBACK: true
    USE_PREMIUM_MODELS: true
  
shinka/minimal:
  <<: *defaults
  kwargs:
    num_generations: 50
  env_vars:
    <<: *env_vars

shinka/debug:
  <<: *defaults
  env_vars:
    <<: *env_vars
    DEBUG: true
    
